#!/bin/csh -f

# author gurjyan
# date 1.7.15

setenv PYTHONPATH $PCLARA_HOME\:$PCLARA_HOME/src/sys\:$PCLARA_HOME/src/base\:$PCLARA_HOME/src/util\:$PCLARA_HOME/examples\:$PCLARA_HOME/examples/engines\:$PCLARA_HOME/example/etc\:$PXMSG_HOME\:$PXMSG_HOME/core\:$PXMSG_HOME/sys\:$PXMSG_HOME/sys/regdis\:$PXMSG_HOME/data\:$PXMSG_HOME/net

cd "$PCLARA_HOME/examples/orchestrators"

if ( $#argv != 3 || $1 == "-h" || $1 == "-help" ) then
    echo ""
    echo "Starts CLARA application (python binding)"
    echo "-------------------------------------"
    echo "synopsis:"
    echo "p_pattern [starting service engine] [data size (bytes)] [composition] "
    echo ""
else
python PatternTester.py $1 $2 $3
endif
