#!/bin/csh -f

# author gurjyan
# date 9.26.14

setenv PYTHONPATH $PCLARA_HOME\:$PCLARA_HOME/src/sys\:$PCLARA_HOME/src/base\:$PCLARA_HOME/src/util\:$PCLARA_HOME/example\:$PCLARA_HOME/example/engines\:$PCLARA_HOME/example/etc

cd "$PCLARA_HOME/src/sys"

if ( $1 == "-h" || $1 == "-help" ) then
    echo ""
    echo "Starts CLARA dpe (python binding)"
    echo "-------------------------------- "
    echo "synopsis: p_dpe"
    echo ""
else
    python Dpe.py
endif
